Drop LOG_FILE support
canonical/identity-platform-admin-ui-operator pull request #111
Opened 2024-11-29 13:12 UTC by nsklikas

IAM-1229

2024-11-29 13:27 UTC, natalian98 submitted a review, later dismissed

2024-12-02 11:10 UTC, pik4ez-canonical requested changes
The changes themselves look fine. But the failing test may need some attention. I was able to reproduce the problem locally.

Please let me know if you think we need to merge these changes without passing the integration tests, as there already exists an [issue](https://github.com/canonical/identity-platform-admin-ui-operator/issues/106) to fix the tests.

2024-12-03 09:39 UTC, pik4ez-canonical approved these changes

2024-12-03 13:48 UTC, nsklikas commented
@natalian98 @pik4ez-canonical tests pass now, can you re-approve?

2024-12-03 13:49 UTC, pik4ez-canonical approved these changes

2024-12-03 13:49 UTC, merged